// @vitest-environment node
import { spawnSync } from "node:child_process";
import { copyFile, mkdir, mkdtemp, readFile, readdir, realpath, rename, rm, symlink, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const script = resolve(process.cwd(), "scripts/copy-ort-assets.mjs");
const fixtureRoots: string[] = [];
const files = [
  ["web/node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs", "ort/ort-wasm-simd-threaded.mjs"],
  ["web/node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm", "ort/ort-wasm-simd-threaded.wasm"],
  ["LICENSE", "legal/LICENSE.txt"],
  ["NOTICE", "legal/NOTICE.txt"],
  ["reports/security/node-production-licenses.json", "legal/THIRD_PARTY_LICENSES.json"],
  ["docs/PRIVACY_NOTICE.md", "legal/PRIVACY_NOTICE.md"],
  ["docs/AI_ASSISTANCE_PUBLIC.md", "legal/AI_ASSISTANCE_LOG.md"],
] as const;

async function fixture() {
  const root = await mkdtemp(join(await realpath(tmpdir()), "plategauge-assets-test-"));
  fixtureRoots.push(root);
  const repository = join(root, "repository");
  const entry = join(repository, "web", "scripts", "copy-ort-assets.mjs");
  await mkdir(dirname(entry), { recursive: true });
  await copyFile(script, entry);
  for (const [source, target] of files) {
    await mkdir(dirname(join(repository, source)), { recursive: true });
    await writeFile(join(repository, source), Buffer.from(`synthetic source bytes: ${source}\n`));
    await mkdir(dirname(join(repository, "web/public", target)), { recursive: true });
    await writeFile(join(repository, "web/public", target), Buffer.from(`previous generated bytes: ${target}\n`));
  }
  return { root, repository, entry, publicDirectory: join(repository, "web/public") };
}

function run(entry: string, preload?: string) {
  return spawnSync(process.execPath, [...(preload ? ["--import", pathToFileURL(preload).href] : []), entry], {
    encoding: "utf8", timeout: 10_000, windowsHide: true,
  });
}

async function previousAssets(publicDirectory: string) {
  for (const [, target] of files) {
    expect(await readFile(join(publicDirectory, target), "utf8")).toBe(`previous generated bytes: ${target}\n`);
  }
}

afterEach(async () => {
  const temporaryRoot = await realpath(tmpdir());
  for (const root of fixtureRoots.splice(0)) {
    // Every junction created by these tests also points inside this isolated fixture root.
    // Validate the exact test root before recursively removing only synthetic test material.
    const canonical = await realpath(root);
    if (!basename(canonical).startsWith("plategauge-assets-test-")
      || relative(temporaryRoot, canonical) !== basename(canonical)) {
      throw new Error(`Refusing unexpected fixture cleanup target: ${canonical}`);
    }
    await rm(canonical, { recursive: true, force: true });
  }
});

describe("asset preparation containment and preservation", () => {
  it("copies exactly the source bytes, supports repeat runs, and leaves no staging debris", async () => {
    const item = await fixture();
    for (let repetition = 0; repetition < 2; repetition += 1) {
      const result = run(item.entry);
      expect(result.status, result.stderr).toBe(0);
      for (const [source, target] of files) {
        expect(await readFile(join(item.publicDirectory, target))).toEqual(await readFile(join(item.repository, source)));
      }
      expect((await readdir(item.publicDirectory)).sort()).toEqual(["legal", "ort"]);
    }
  });

  it.each([files[0][0], files[2][0], files[6][0]])("preserves all previous assets when required input %s is missing", async (missing) => {
    const item = await fixture();
    await unlink(join(item.repository, missing));
    expect(run(item.entry).status).not.toBe(0);
    await previousAssets(item.publicDirectory);
    expect((await readdir(item.publicDirectory)).sort()).toEqual(["legal", "ort"]);
  });

  it("creates a missing public directory only after every input has passed preflight", async () => {
    const item = await fixture();
    await rename(item.publicDirectory, join(item.root, "previous-public-fixture"));
    const result = run(item.entry);
    expect(result.status, result.stderr).toBe(0);
    for (const [source, target] of files) {
      expect(await readFile(join(item.publicDirectory, target))).toEqual(await readFile(join(item.repository, source)));
    }
  });

  it.each(["ort", "legal"])("refuses unexplained files in %s without deleting them or replacing any assets", async (group) => {
    const item = await fixture();
    const note = join(item.publicDirectory, group, "personal-notes.txt");
    await writeFile(note, "keep this synthetic user file");
    const result = run(item.entry);
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("Refusing unexplained");
    expect(await readFile(note, "utf8")).toBe("keep this synthetic user file");
    await previousAssets(item.publicDirectory);
  });

  it("refuses a linked public parent and leaves its destination untouched", async () => {
    const item = await fixture();
    const untouched = join(item.root, "outside-repository");
    await rename(item.publicDirectory, untouched);
    await symlink(untouched, item.publicDirectory, process.platform === "win32" ? "junction" : "dir");
    const result = run(item.entry);
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("Refusing non-directory or linked asset path");
    await previousAssets(untouched);
    expect((await readdir(untouched)).sort()).toEqual(["legal", "ort"]);
  });

  it.each(["ort", "legal"])("refuses a linked %s target without touching its destination", async (group) => {
    const item = await fixture();
    const target = join(item.publicDirectory, group);
    const untouched = join(item.root, `outside-${group}`);
    await rename(target, untouched);
    await symlink(untouched, target, process.platform === "win32" ? "junction" : "dir");
    const result = run(item.entry);
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("Refusing non-directory or linked asset path");
    await previousAssets(item.publicDirectory);
  });

  it("refuses linked sources outside the repository before replacing prior assets", async () => {
    const item = await fixture();
    const packageDirectory = join(item.repository, "web/node_modules/onnxruntime-web");
    const outsidePackage = join(item.root, "outside-package");
    await rename(packageDirectory, outsidePackage);
    await symlink(outsidePackage, packageDirectory, process.platform === "win32" ? "junction" : "dir");
    const result = run(item.entry);
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("external asset source");
    await previousAssets(item.publicDirectory);
  });

  it("permits pnpm-style package directory links resolved inside the repository", async () => {
    const item = await fixture();
    const packageDirectory = join(item.repository, "web/node_modules/onnxruntime-web");
    const internalPackage = join(item.repository, "web/node_modules/.pnpm/synthetic-runtime");
    await mkdir(dirname(internalPackage), { recursive: true });
    await rename(packageDirectory, internalPackage);
    await symlink(internalPackage, packageDirectory, process.platform === "win32" ? "junction" : "dir");
    const result = run(item.entry);
    expect(result.status, result.stderr).toBe(0);
    expect(await readFile(join(item.publicDirectory, files[0][1]))).toEqual(await readFile(join(item.repository, files[0][0])));
  });

  it("refuses an existing preparation lock without taking ownership or modifying assets", async () => {
    const item = await fixture();
    await mkdir(join(item.publicDirectory, ".plategauge-assets.lock"));
    const result = run(item.entry);
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("already running or an interrupted lock remains");
    await previousAssets(item.publicDirectory);
    expect(await readdir(item.publicDirectory)).toContain(".plategauge-assets.lock");
  });

  it("restores both prior directories after a synthetic second-promotion failure", async () => {
    const item = await fixture();
    const preload = join(item.root, "promotion-failure.mjs");
    // Fault injection wraps only the built-in rename; the copied production script is unchanged.
    await writeFile(preload, `import fs from "node:fs";
import { syncBuiltinESMExports } from "node:module";
import { basename } from "node:path";
const original = fs.promises.rename;
fs.promises.rename = async (source, target) => {
  if (basename(source) === "legal" && String(source).includes(".plategauge-assets-stage-")) {
    throw new Error("synthetic second-promotion failure");
  }
  return original(source, target);
};
syncBuiltinESMExports();
`);
    const result = run(item.entry, preload);
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("synthetic second-promotion failure");
    await previousAssets(item.publicDirectory);
    expect((await readdir(item.publicDirectory)).sort()).toEqual(["legal", "ort"]);
  });

  it("preserves the original failure when cleanup also fails", async () => {
    const item = await fixture();
    const preload = join(item.root, "cleanup-failure.mjs");
    await writeFile(preload, `import fs from "node:fs";
import { syncBuiltinESMExports } from "node:module";
import { basename } from "node:path";
const originalRename = fs.promises.rename;
const originalRmdir = fs.promises.rmdir;
fs.promises.rename = async (source, target) => {
  if (basename(source) === "legal" && String(source).includes(".plategauge-assets-stage-")) {
    throw new Error("synthetic original promotion failure");
  }
  return originalRename(source, target);
};
fs.promises.rmdir = async (path) => {
  if (basename(path) === "ort" && String(path).includes(".plategauge-assets-stage-")) {
    throw new Error("synthetic cleanup failure");
  }
  return originalRmdir(path);
};
syncBuiltinESMExports();
`);
    const result = run(item.entry, preload);
    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("synthetic original promotion failure");
    expect(result.stderr).toContain("synthetic cleanup failure");
    await previousAssets(item.publicDirectory);
    const remaining = await readdir(item.publicDirectory);
    expect(remaining).not.toContain(".plategauge-assets.lock");
    expect(remaining.some((name) => name.startsWith(".plategauge-assets-stage-"))).toBe(true);
  });
});
