import { describe, expect, it, vi } from "vitest";
import { EXPERIMENTAL_MODEL } from "./contract";
import { readModelBytes } from "./modelBytes";

const url = new URL("https://aldaqrouqtaysir.github.io/plategauge/models/plategauge.onnx");
function fixture(chunks: Uint8Array[], overrides: Partial<Response> = {}) {
  const cancel = vi.fn().mockResolvedValue(undefined), releaseLock = vi.fn();
  const read = vi.fn(() => {
    const value = chunks.shift();
    return Promise.resolve(value ? { done: false, value } : { done: true });
  });
  const getReader = vi.fn(() => ({ read, cancel, releaseLock }));
  const response = {
    ok: true, status: 200, type: "basic", redirected: false, url: url.href,
    headers: new Headers({ "content-type": "application/octet-stream" }),
    body: { getReader, cancel }, ...overrides,
  } as unknown as Response;
  return { response, read, getReader, cancel, releaseLock };
}

describe("bounded pinned model body (generated bytes only)", () => {
  it("reads an exact-length chunked body without arrayBuffer or unbounded concatenation", async () => {
    const head = new Uint8Array(17).fill(2), tail = new Uint8Array(EXPERIMENTAL_MODEL.bytes - 17).fill(3);
    const f = fixture([head, tail]);
    const buffer = await readModelBytes(f.response, url), bytes = new Uint8Array(buffer);
    expect(bytes).toHaveLength(EXPERIMENTAL_MODEL.bytes); expect(bytes[0]).toBe(2); expect(bytes.at(-1)).toBe(3);
    expect(f.read).toHaveBeenCalledTimes(3); expect(f.releaseLock).toHaveBeenCalledOnce(); expect(f.cancel).not.toHaveBeenCalled();
    expect(head[0]).toBe(2); expect(tail[0]).toBe(3);
    bytes.fill(0);
  });
  it.each([
    { status: 206 }, { ok: false }, { redirected: true }, { type: "cors" as ResponseType },
    { type: "opaque" as ResponseType }, { url: "https://evil.example/model.onnx" }, { url: `${url.href}?redirected=1` },
  ])("rejects unsafe response metadata %# before acquiring a reader", async (override) => {
    const f = fixture([], override);
    await expect(readModelBytes(f.response, url)).rejects.toThrow("response");
    expect(f.getReader).not.toHaveBeenCalled(); expect(f.cancel).toHaveBeenCalledOnce();
  });
  it.each([
    { "content-type": "text/html" }, { "content-type": "text/plain" }, { "content-type": "application/json" },
    { "content-type": "application/octet-stream", "content-length": String(EXPERIMENTAL_MODEL.bytes + 1) },
    { "content-type": "application/octet-stream", "content-length": "-1" },
    { "content-type": "application/octet-stream", "content-length": "1e9" },
  ])("rejects unsafe headers %# before body allocation", async (headers) => {
    const f = fixture([], { headers: new Headers(headers as Record<string, string>) });
    await expect(readModelBytes(f.response, url)).rejects.toThrow("headers");
    expect(f.getReader).not.toHaveBeenCalled(); expect(f.cancel).toHaveBeenCalledOnce();
  });
  it.each([null, "", "   "])("accepts absent or empty MIME %j with an exact pinned-size body", async (contentType) => {
    const headers = new Headers();
    if (contentType !== null) headers.set("content-type", contentType);
    const f = fixture([new Uint8Array(EXPERIMENTAL_MODEL.bytes)], { headers });
    const buffer = await readModelBytes(f.response, url);
    expect(buffer.byteLength).toBe(EXPERIMENTAL_MODEL.bytes);
    expect(f.read).toHaveBeenCalledTimes(2); expect(f.releaseLock).toHaveBeenCalledOnce();
    expect(f.cancel).not.toHaveBeenCalled();
    new Uint8Array(buffer).fill(0);
  });
  it("still rejects a missing-MIME body with the wrong byte length", async () => {
    const f = fixture([new Uint8Array(3)], { headers: new Headers() });
    await expect(readModelBytes(f.response, url)).rejects.toThrow("size");
    expect(f.cancel).toHaveBeenCalledOnce(); expect(f.releaseLock).toHaveBeenCalledOnce();
  });
  it("rejects a missing body", async () => {
    await expect(readModelBytes(fixture([], { body: null }).response, url)).rejects.toThrow("body missing");
  });
  it.each([0, 5, EXPERIMENTAL_MODEL.bytes - 1])("rejects a truncated %i-byte stream and cancels/releases it", async (size) => {
    const f = fixture([new Uint8Array(size)]);
    await expect(readModelBytes(f.response, url)).rejects.toThrow("size");
    expect(f.cancel).toHaveBeenCalledOnce(); expect(f.releaseLock).toHaveBeenCalledOnce();
  });
  it("rejects a chunk that would exceed the fixed buffer without reading further", async () => {
    const f = fixture([new Uint8Array(EXPERIMENTAL_MODEL.bytes), new Uint8Array(1), new Uint8Array(10)]);
    await expect(readModelBytes(f.response, url)).rejects.toThrow("bound");
    expect(f.read).toHaveBeenCalledTimes(2); expect(f.cancel).toHaveBeenCalledOnce(); expect(f.releaseLock).toHaveBeenCalledOnce();
  });
  it("releases the lock even if cancellation itself rejects", async () => {
    const f = fixture([]); f.cancel.mockRejectedValue(new Error("synthetic cancellation failure"));
    await expect(readModelBytes(f.response, url)).rejects.toThrow("size");
    expect(f.releaseLock).toHaveBeenCalledOnce();
  });
  it("cancels and releases a stream read failure", async () => {
    const f = fixture([]); f.read.mockRejectedValue(new Error("synthetic stream failure"));
    await expect(readModelBytes(f.response, url)).rejects.toThrow("stream failure");
    expect(f.cancel).toHaveBeenCalledOnce(); expect(f.releaseLock).toHaveBeenCalledOnce();
  });
});
